name: cherry_craft_api

description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  bson: ^5.0.3
  envied: ^0.5.3
  http: ^1.2.0
  mysql_client: ^0.0.27
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
